version: 3
dotenv: ['.env']
tasks:
#  Up & Down for all the services mentioned in Docker-Compose
  all:
    desc: Start all services
    cmds:
      - docker-compose --profile default up -d
  shutdown:
    desc: Stop all services
    cmds:
      - docker-compose --profile default down
      - docker system prune -f
      - docker volume prune -f
      - echo "PRUNED DANGLING VOLUMES & CONTAINERS"
  running:
    desc: Show compose running services
    cmds:
      - docker-compose ps -a
  marathon:
    desc: Show all running services
    cmds:
      - docker ps -a

  ##################################################
# MongoDB Commands
  mongodb-up:
    desc: Start MongoDb
    cmds:
      - docker-compose --profile default up -d mongodb
  mongodb-logs:
    desc: Log MongoDb
    cmds:
      - docker logs -f $MONGO_CONTAINER_NAME
  mongodb-down:
    desc: Stop MongoDb
    cmds:
      - docker-compose --profile default down mongodb

##################################################
# ElasticSearch Commands
  elasticsearch-setup:
    desc: Start ElasticSearch Setup for SSL/TLS Setup for Kibana & Elasticsearch
    cmds:
      - docker-compose --profile default up -d elasticsearch
      - docker-compose --profile setup_elk up elasticsearch-setup
      - docker container rm $ELASTICSEARCH_SETUP_CONTAINER_NAME
      - echo "ElasticSearch Setup Done!"
  elasticsearch-logs:
    desc:  Log ElasticSearch
    cmds:
      - docker logs -f $ELASTICSEARCH_CONTAINER_NAME
  elasticsearch-down:
    desc: Stop ElasticSearch
    cmds:
      - docker-compose --profile default down elasticsearch
  elasticsearch-up:
    desc: Start ElasticSearch
    cmds:
      - docker-compose --profile default up -d elasticsearch


##################################################
  # EMQX Commands
  emqx-up:
    desc: Start Emqx broker
    cmds:
      - docker-compose --profile default up -d emqx
  emqx-logs:
    desc:  Log Emqx broker
    cmds:
      - docker logs -f $EMQX_CONTAINER_NAME
  emqx-down:
    desc: Stop Emqx broker
    cmds:
      - docker-compose --profile default down emqx

##################################################
  # Kibana Commands
  kibana-up:
    desc: Start Kibana
    cmds:
      - docker-compose --profile default up -d kibana
  kibana-logs:
    desc:  Log Kibana
    cmds:
      - docker logs -f $KIBANA_CONTAINER_NAME
  kibana-down:
    desc: Stop Kibana
    cmds:
      - docker-compose --profile default down kibana

##################################################
  # Postgresql Commands
  postgresql-up:
    desc: Start Postgresql
    cmds:
      - docker-compose --profile default up -d postgresql
  postgresql-logs:
    desc:  Log Postgresql
    cmds:
      - docker logs -f $POSTGRESQL_CONTAINER_NAME
  postgresql-down:
    desc: Stop Postgresql
    cmds:
      - docker-compose --profile default down postgresql

##################################################
  # Redis Commands
  redis-up:
    desc: Start Redis
    cmds:
      - docker-compose --profile default up -d redis
  redis-logs:
    desc:  Log Redis
    cmds:
      - docker logs -f $REDIS_CONTAINER_NAME
  redis-down:
    desc: Stop Redis
    cmds:
      - docker-compose --profile default down redis

##################################################
  # Kafka Commands with Authentication & TLS certs
  kafka-up:
    desc: Start Kafka
    cmds:
      - docker-compose --profile default up -d kafka
  kafka-logs:
    desc:  Log Kafka
    cmds:
      - docker logs -f $KAFKA_CONTAINER_NAME
  kafka-down:
    desc: Stop Kafka
    cmds:
      - docker-compose --profile default down kafka

##################################################
  # Simple Kafka Commands : No Auth or Certs
  safka-up:
    desc: Start Simple Kafka
    cmds:
      - docker-compose --profile default up -d simple-kafka
  safka-logs:
    desc:  Log Simple Kafka
    cmds:
      - docker logs -f $SAFKA_CONTAINER_NAME
  safka-down:
    desc: Stop Simple Kafka
    cmds:
      - docker-compose --profile default down simple-kafka